# Generated by Django 5.0.1 on 2024-01-27 17:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multigtfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageTravelTime',
            fields=[
                ('from_stop_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('to_stop_code', models.CharField(max_length=255)),
                ('bin', models.IntegerField()),
                ('average_travel_time', models.DurationField()),
                ('hour', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawVehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.SmallIntegerField()),
                ('route_id', models.CharField(db_index=True, max_length=5)),
                ('route_name', models.CharField(max_length=5, null=True)),
                ('brigade_id', models.SmallIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StopPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_code', models.CharField(db_index=True, max_length=255)),
                ('made_at_next_stoptime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='multigtfs.stoptime')),
                ('stoptime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.stoptime')),
            ],
        ),
        migrations.CreateModel(
            name='StopTimePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('time', models.DateTimeField()),
                ('stop_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepred.stopprediction')),
            ],
        ),
        migrations.CreateModel(
            name='TripInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.trip')),
            ],
        ),
        migrations.AddField(
            model_name='stopprediction',
            name='trip_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepred.tripinstance'),
        ),
        migrations.CreateModel(
            name='VehicleStopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('stoptime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.stoptime')),
                ('trip_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepred.tripinstance')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCache',
            fields=[
                ('vehicle_id', models.SmallIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('shape_dist', models.FloatField()),
                ('next_stoptime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.stoptime')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timepred.rawvehicledata')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.route')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.trip')),
                ('trip_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timepred.tripinstance')),
                ('current_vehiclestoptime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timepred.vehiclestoptime')),
            ],
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_code', models.CharField(db_index=True, max_length=255)),
                ('to_stop_code', models.CharField(db_index=True, max_length=255)),
                ('travel_time', models.DurationField()),
                ('from_vehiclestoptime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_vehiclestoptimes', to='timepred.vehiclestoptime')),
                ('to_vehiclestoptime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_vehiclestoptimes', to='timepred.vehiclestoptime')),
            ],
        ),
    ]
