# Generated by Django 5.0.1 on 2024-01-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timepred', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stopprediction',
            old_name='made_at_next_stoptime',
            new_name='made_at',
        ),
        migrations.AlterField(
            model_name='averagetraveltime',
            name='from_stop_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='averagetraveltime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
