# Generated by Django 5.0.1 on 2024-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timepred",
            "0002_rename_made_at_next_stoptime_stopprediction_made_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="averagetraveltime",
            name="from_stop_code",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="averagetraveltime",
            name="to_stop_code",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
